export const COLUMNS = {
  id: 'ID',
  code: 'Código',
  description: 'Descrição',
  unit: 'Unidade',
  ncm: 'NCM',
  price: 'Preço',
  status: 'Situação',
  stock: 'Estoque',
  costPrice: 'Preço de custo',
  maxStock: 'Estoque máximo',
  minStock: 'Estoque mínimo',
  netWeight: 'Peso líquido (Kg)',
  grossWeight: 'Peso bruto (Kg)',
  gtin: 'GTIN/EAN',
  width: 'Largura do produto',
  height: 'Altura do Produto',
  depth: 'Profundidade do produto',
  variation: 'Produto Variação',
  tags: 'Grupo de Tags/Tags',
  parentCode: 'Código Pai',
  brand: 'Marca',
  shortDescription: 'Descrição Curta',
  imageUrls: 'URL Imagens Externas',
  category: 'Categoria do produto',
  additionalInfo: 'Informações Adicionais',
} as const;

export const REQUIRED_HEADERS = [
  COLUMNS.code,
  COLUMNS.description,
  COLUMNS.status,
  COLUMNS.price,
  COLUMNS.parentCode,
  COLUMNS.variation,
  COLUMNS.imageUrls,
] as const;

export const PROPAGABLE_FIELDS = [
  { column: COLUMNS.tags, label: 'Grupo de Tags/Tags' },
  { column: COLUMNS.category, label: 'Categoria do produto' },
  { column: COLUMNS.brand, label: 'Marca' },
  { column: COLUMNS.status, label: 'Situação' },
  { column: COLUMNS.price, label: 'Preço' },
  { column: COLUMNS.costPrice, label: 'Preço de custo' },
  { column: COLUMNS.minStock, label: 'Estoque mínimo' },
  { column: COLUMNS.maxStock, label: 'Estoque máximo' },
  { column: COLUMNS.netWeight, label: 'Peso líquido' },
  { column: COLUMNS.grossWeight, label: 'Peso bruto' },
  { column: COLUMNS.width, label: 'Largura' },
  { column: COLUMNS.height, label: 'Altura' },
  { column: COLUMNS.depth, label: 'Profundidade' },
  { column: COLUMNS.ncm, label: 'NCM' },
  { column: COLUMNS.shortDescription, label: 'Descrição Curta' },
  { column: COLUMNS.additionalInfo, label: 'Informações Adicionais' },
  { column: COLUMNS.imageUrls, label: 'URL Imagens Externas' },
] as const;
